### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ClientException

### ISSUE THREAD

**Issue by smartcmsteam** [krizalys/onedrive-php-sdk#113]
Hello,

After authentication i get this error:

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://login.microsoftonline.com/common/oauth2/v2.0/token` resulted in a `401 Unauthorized` response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being se (truncated...) in /home/plgroup/newapp.plgroup.ie/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /home/plgroup/newapp.plgroup.ie/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL) #1 /home/plgroup/newapp.plgroup.ie/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /home/plgroup/newapp.plgroup.ie/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 /home/plgroup/newapp.plgroup.ie/vendor/guzzlehttp/promise in /home/plgroup/newapp.plgroup.ie/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

How to fix it?

Thanks

**Comment by GenieTim** [comment]
First, try to get the full response, such that the error is not truncated. There, you should see an error message telling you what went wrong during the authentication.
